export const DEFAULT_CATEGORY_ALL_CODE = "0000";
export const DEFAULT_TABLE_STATUS_UPDATE_TIME = 1000*30;
export const DEFAULT_FIVE_MIN_STATUS_UPDATE_TIME = 1000*60*5;
export const META_SET_MENU_SEPARATE_CODE_LIST = ["09"];
export const PAY_SEPRATE_AMT_LIMIT = 50000;

export const SUCCESS_STRING = "SUCCESS";
export const SUCCESS_CODE = "0000";
export const ERROR_STRING = "ERROR";
export const ERROR_CODE = "XXXX";
